# Generated by Django 5.0.2 on 2025-03-18 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Parça Adı')),
                ('team_type', models.CharField(choices=[('BODY', 'Gövde'), ('WING', 'Kanat'), ('TAIL', 'Kuyruk'), ('AVIONICS', 'Aviyonik'), ('ASSEMBLY', 'Montaj')], max_length=20, verbose_name='Üretici Takım Tipi')),
                ('aircraft_type', models.CharField(choices=[('TB2', 'TB2'), ('TB3', 'TB3'), ('AKINCI', 'AKINCI'), ('KIZILELMA', 'KIZILELMA')], max_length=20, verbose_name='Hava Aracı Tipi')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stok Miktarı')),
                ('minimum_stock', models.PositiveIntegerField(default=5, verbose_name='Minimum Stok Miktarı')),
                ('is_low_stock', models.BooleanField(default=False, verbose_name='Düşük Stok')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Parça',
                'verbose_name_plural': 'Parçalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_type', models.CharField(choices=[('TB2', 'TB2'), ('TB3', 'TB3'), ('AKINCI', 'AKINCI'), ('KIZILELMA', 'KIZILELMA')], max_length=20, verbose_name='Hava Aracı Tipi')),
                ('is_complete', models.BooleanField(default=False, verbose_name='Tamamlandı mı?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma Tarihi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_aircrafts', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Hava Aracı',
                'verbose_name_plural': 'Hava Araçları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AircraftPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='added_parts', to=settings.AUTH_USER_MODEL, verbose_name='Ekleyen')),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aircraft_parts', to='production.aircraft', verbose_name='Hava Aracı')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aircraft_parts', to='production.part', verbose_name='Parça')),
            ],
            options={
                'verbose_name': 'Hava Aracı Parçası',
                'verbose_name_plural': 'Hava Aracı Parçaları',
                'ordering': ['added_at'],
                'unique_together': {('aircraft', 'part')},
            },
        ),
        migrations.AddField(
            model_name='aircraft',
            name='parts',
            field=models.ManyToManyField(related_name='aircrafts', through='production.AircraftPart', to='production.part', verbose_name='Parçalar'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Takım Adı')),
                ('team_type', models.CharField(choices=[('BODY', 'Gövde'), ('WING', 'Kanat'), ('TAIL', 'Kuyruk'), ('AVIONICS', 'Aviyonik'), ('ASSEMBLY', 'Montaj')], max_length=20, verbose_name='Takım Tipi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('members', models.ManyToManyField(blank=True, related_name='team_members', to=settings.AUTH_USER_MODEL, verbose_name='Üyeler')),
            ],
            options={
                'verbose_name': 'Takım',
                'verbose_name_plural': 'Takımlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Miktar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productions', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productions', to='production.part', verbose_name='Üretilen Parça')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productions', to='production.team', verbose_name='Üretici Takım')),
            ],
            options={
                'verbose_name': 'Üretim',
                'verbose_name_plural': 'Üretimler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='aircraft',
            name='assembly_team',
            field=models.ForeignKey(blank=True, limit_choices_to={'team_type': 'ASSEMBLY'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='production.team', verbose_name='Montaj Takımı'),
        ),
    ]
