# Generated by Django 5.0.2 on 2025-03-18 16:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='aircraftpart',
            index=models.Index(fields=['aircraft', 'part'], name='production__aircraf_e787d2_idx'),
        ),
        migrations.AddIndex(
            model_name='aircraftpart',
            index=models.Index(fields=['added_at'], name='production__added_a_a50d92_idx'),
        ),
        migrations.AddIndex(
            model_name='production',
            index=models.Index(fields=['team'], name='production__team_id_056a2a_idx'),
        ),
        migrations.AddIndex(
            model_name='production',
            index=models.Index(fields=['part'], name='production__part_id_d3ba75_idx'),
        ),
        migrations.AddIndex(
            model_name='production',
            index=models.Index(fields=['created_at'], name='production__created_ad1a55_idx'),
        ),
    ]
