# Generated by Django 5.0.1 on 2025-03-14 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aircraftpart',
            options={'verbose_name': 'Uçak Parçası', 'verbose_name_plural': 'Uçak Parçaları'},
        ),
        migrations.AddField(
            model_name='aircraft',
            name='assembly_team',
            field=models.ForeignKey(blank=True, limit_choices_to={'team_type': 'ASSEMBLY'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assembled_aircrafts', to='production.team', verbose_name='Montaj Takımı'),
        ),
        migrations.AddField(
            model_name='aircraftpart',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ekleyen'),
        ),
        migrations.AddField(
            model_name='part',
            name='aircraft_type',
            field=models.CharField(choices=[('F16', 'F-16'), ('F35', 'F-35'), ('F22', 'F-22')], default='1', max_length=10, verbose_name='Uçak Tipi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='minimum_stock',
            field=models.PositiveIntegerField(default=5, verbose_name='Minimum Stok'),
        ),
        migrations.AddField(
            model_name='production',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Üreten'),
        ),
        migrations.AddField(
            model_name='team',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='aircraft_type',
            field=models.CharField(choices=[('F16', 'F-16'), ('F35', 'F-35'), ('F22', 'F-22')], max_length=10, verbose_name='Uçak Tipi'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='aircraftpart',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.part', verbose_name='Parça'),
        ),
        migrations.AlterField(
            model_name='part',
            name='team_type',
            field=models.CharField(choices=[('AVIONICS', 'Aviyonik'), ('BODY', 'Gövde'), ('WING', 'Kanat'), ('TAIL', 'Kuyruk'), ('ASSEMBLY', 'Montaj')], max_length=20, verbose_name='Üretici Takım'),
        ),
        migrations.AlterField(
            model_name='production',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.part', verbose_name='Üretilen Parça'),
        ),
        migrations.AlterField(
            model_name='production',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.team', verbose_name='Üretici Takım'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_type',
            field=models.CharField(choices=[('AVIONICS', 'Aviyonik'), ('BODY', 'Gövde'), ('WING', 'Kanat'), ('TAIL', 'Kuyruk'), ('ASSEMBLY', 'Montaj')], max_length=20, verbose_name='Takım Tipi'),
        ),
        migrations.AlterUniqueTogether(
            name='part',
            unique_together={('name', 'team_type', 'aircraft_type')},
        ),
    ]
