# Generated by Django 5.0.2 on 2025-03-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_alter_aircraftpart_options_aircraft_assembly_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='aircraft_type',
            field=models.CharField(choices=[('TB2', 'TB2'), ('TB3', 'TB3'), ('AKINCI', 'AKINCI'), ('KIZILELMA', 'KIZILELMA')], max_length=10, verbose_name='Uçak Tipi'),
        ),
        migrations.AlterField(
            model_name='part',
            name='aircraft_type',
            field=models.CharField(choices=[('TB2', 'TB2'), ('TB3', 'TB3'), ('AKINCI', 'AKINCI'), ('KIZILELMA', 'KIZILELMA')], max_length=10, verbose_name='Uçak Tipi'),
        ),
    ]
