# Generated by Django 5.0.2 on 2025-03-14 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_alter_aircraft_aircraft_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productions', to='production.team', verbose_name='Üretici Takım'),
        ),
    ]
