# Generated by Django 5.0.2 on 2025-03-15 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_alter_production_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aircraft',
            options={'ordering': ['-created_at'], 'verbose_name': 'Hava Aracı', 'verbose_name_plural': 'Hava Araçları'},
        ),
        migrations.AlterModelOptions(
            name='aircraftpart',
            options={'ordering': ['added_at'], 'verbose_name': 'Hava Aracı Parçası', 'verbose_name_plural': 'Hava Aracı Parçaları'},
        ),
        migrations.AlterUniqueTogether(
            name='part',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_aircrafts', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan'),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='Tamamlandı mı?'),
        ),
        migrations.AddField(
            model_name='part',
            name='is_low_stock',
            field=models.BooleanField(default=False, verbose_name='Düşük Stok'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='aircraft_type',
            field=models.CharField(choices=[('TB2', 'TB2'), ('TB3', 'TB3'), ('AKINCI', 'AKINCI'), ('KIZILELMA', 'KIZILELMA')], max_length=20, verbose_name='Hava Aracı Tipi'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='assembly_team',
            field=models.ForeignKey(blank=True, limit_choices_to={'team_type': 'ASSEMBLY'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='production.team', verbose_name='Montaj Takımı'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='parts',
            field=models.ManyToManyField(related_name='aircrafts', through='production.AircraftPart', to='production.part', verbose_name='Parçalar'),
        ),
        migrations.AlterField(
            model_name='aircraftpart',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='added_parts', to=settings.AUTH_USER_MODEL, verbose_name='Ekleyen'),
        ),
        migrations.AlterField(
            model_name='aircraftpart',
            name='aircraft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aircraft_parts', to='production.aircraft', verbose_name='Hava Aracı'),
        ),
        migrations.AlterField(
            model_name='aircraftpart',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aircraft_parts', to='production.part', verbose_name='Parça'),
        ),
        migrations.AlterField(
            model_name='part',
            name='aircraft_type',
            field=models.CharField(choices=[('TB2', 'TB2'), ('TB3', 'TB3'), ('AKINCI', 'AKINCI'), ('KIZILELMA', 'KIZILELMA')], max_length=20, verbose_name='Hava Aracı Tipi'),
        ),
        migrations.AlterField(
            model_name='part',
            name='minimum_stock',
            field=models.PositiveIntegerField(default=5, verbose_name='Minimum Stok Miktarı'),
        ),
        migrations.AlterField(
            model_name='part',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Stok Miktarı'),
        ),
        migrations.AlterField(
            model_name='part',
            name='team_type',
            field=models.CharField(choices=[('BODY', 'Gövde'), ('WING', 'Kanat'), ('ENGINE', 'Motor'), ('ELECTRONIC', 'Elektronik'), ('ASSEMBLY', 'Montaj')], max_length=20, verbose_name='Üretici Takım Tipi'),
        ),
        migrations.AlterField(
            model_name='production',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='production',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productions', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan'),
        ),
        migrations.AlterField(
            model_name='production',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productions', to='production.part', verbose_name='Üretilen Parça'),
        ),
        migrations.AlterField(
            model_name='production',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Miktar'),
        ),
        migrations.AlterField(
            model_name='production',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productions', to='production.team', verbose_name='Üretici Takım'),
        ),
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='team_members', to=settings.AUTH_USER_MODEL, verbose_name='Üyeler'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_type',
            field=models.CharField(choices=[('BODY', 'Gövde'), ('WING', 'Kanat'), ('ENGINE', 'Motor'), ('ELECTRONIC', 'Elektronik'), ('ASSEMBLY', 'Montaj')], max_length=20, verbose_name='Takım Tipi'),
        ),
        migrations.AlterUniqueTogether(
            name='part',
            unique_together={('name', 'aircraft_type')},
        ),
    ]
