# Generated by Django 5.0.2 on 2025-03-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_alter_aircraft_options_alter_aircraftpart_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='part',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='part',
            name='team_type',
            field=models.CharField(choices=[('BODY', 'Gövde'), ('WING', 'Kanat'), ('TAIL', 'Kuyruk'), ('AVIONICS', 'Aviyonik'), ('ASSEMBLY', 'Montaj')], max_length=20, verbose_name='Üretici Takım Tipi'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_type',
            field=models.CharField(choices=[('BODY', 'Gövde'), ('WING', 'Kanat'), ('TAIL', 'Kuyruk'), ('AVIONICS', 'Aviyonik'), ('ASSEMBLY', 'Montaj')], max_length=20, verbose_name='Takım Tipi'),
        ),
    ]
