# Generated by Django 5.0.1 on 2025-03-14 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_type', models.CharField(choices=[('TB2', 'Bayraktar TB2'), ('TB3', 'Bayraktar TB3'), ('AKINCI', 'Bayraktar AKINCI'), ('KIZILELMA', 'Bayraktar KIZILELMA')], max_length=20, verbose_name='Uçak Tipi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Başlangıç Tarihi')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma Tarihi')),
            ],
            options={
                'verbose_name': 'Uçak',
                'verbose_name_plural': 'Uçaklar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Parça Adı')),
                ('team_type', models.CharField(choices=[('AVIONICS', 'Aviyonik Takımı'), ('BODY', 'Gövde Takımı'), ('WING', 'Kanat Takımı'), ('TAIL', 'Kuyruk Takımı')], max_length=20, verbose_name='Üretici Takım')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stok')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Parça',
                'verbose_name_plural': 'Parçalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AircraftPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi')),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.aircraft', verbose_name='Uçak')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.part', verbose_name='Parça')),
            ],
            options={
                'verbose_name': 'Uçak Parçası',
                'verbose_name_plural': 'Uçak Parçaları',
                'ordering': ['added_at'],
                'unique_together': {('aircraft', 'part')},
            },
        ),
        migrations.AddField(
            model_name='aircraft',
            name='parts',
            field=models.ManyToManyField(through='production.AircraftPart', to='production.part', verbose_name='Parçalar'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Takım Adı')),
                ('team_type', models.CharField(choices=[('AVIONICS', 'Aviyonik Takımı'), ('BODY', 'Gövde Takımı'), ('WING', 'Kanat Takımı'), ('TAIL', 'Kuyruk Takımı'), ('ASSEMBLY', 'Montaj Takımı')], max_length=20, verbose_name='Takım Tipi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('members', models.ManyToManyField(related_name='team_members', to=settings.AUTH_USER_MODEL, verbose_name='Üyeler')),
            ],
            options={
                'verbose_name': 'Takım',
                'verbose_name_plural': 'Takımlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Miktar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Üretim Tarihi')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.part', verbose_name='Parça')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.team', verbose_name='Takım')),
            ],
            options={
                'verbose_name': 'Üretim',
                'verbose_name_plural': 'Üretimler',
                'ordering': ['-created_at'],
            },
        ),
    ]
